### ISSUE TITLE
Make tests fail if there are exceptions

### ISSUE THREAD

**Issue by monochromata** [amharrison/commonreality#3]
The current state is this:

---
##  T E S T S

Running org.commonreality.time.OwnedClockTest

Jan 08, 2016 9:32:13 PM org.commonreality.time.impl.BasicClock waitForTime
WARNING: time has already elapsed, forcing firing
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.059 sec
Running org.commonreality.time.BasicClockTest
Jan 08, 2016 9:32:13 PM org.commonreality.time.impl.BasicClock waitForTime
WARNING: time has already elapsed, forcing firing
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec
Running org.commonreality.time.WrappedClockTest
Jan 08, 2016 9:32:13 PM org.commonreality.time.impl.BasicClock waitForTime
WARNING: time has already elapsed, forcing firing
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 sec
Running org.commonreality.reality.RealityTest

Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.impl.BaseAcknowledgementMessage): {BaseAcknowledgementMessage:[REALITY:1:Reality:940181955]}
Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.impl.BaseAcknowledgementMessage): {BaseAcknowledgementMessage:[REALITY:1:Reality:940181955]}
Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.impl.BaseAcknowledgementMessage): {BaseAcknowledgementMessage:[REALITY:1:Reality:940181955]}
Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.impl.BaseAcknowledgementMessage): {BaseAcknowledgementMessage:[REALITY:1:Reality:940181955]}
Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.command.control.ControlAcknowledgement): {ControlAcknowledgement:[REALITY:1:Reality:940181955]}:STARTED
Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.command.control.ControlAcknowledgement): {ControlAcknowledgement:[REALITY:1:Reality:940181955]}:STARTED
Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.command.control.ControlAcknowledgement): {ControlAcknowledgement:[REALITY:1:Reality:940181955]}:STOPPED
Jan 08, 2016 9:32:14 PM org.commonreality.mina.service.ClientService$3 handleMessage
SEVERE: Received unexpected message(org.commonreality.net.message.command.control.ControlAcknowledgement): {ControlAcknowledgement:[REALITY:1:Reality:940181955]}:STOPPED
Jan 08, 2016 9:32:14 PM org.commonreality.participant.impl.handlers.ControlHandler accept
SEVERE: Failed to set state RESET
java.lang.NullPointerException
    at org.commonreality.participant.impl.handlers.ControlHandler.setState(ControlHandler.java:117)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:186)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:32)
    at org.commonreality.mina.service.ClientService$5.handleMessage(ClientService.java:164)
    at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:232)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
    at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
    at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:780)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:772)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:714)
    at org.commonreality.executor.GeneralThreadFactory$1.run(GeneralThreadFactory.java:85)
    at java.lang.Thread.run(Thread.java:745)

Jan 08, 2016 9:32:14 PM org.commonreality.participant.impl.handlers.ControlHandler accept
SEVERE: Failed to set state RESET
java.lang.NullPointerException
    at org.commonreality.participant.impl.handlers.ControlHandler.setState(ControlHandler.java:117)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:186)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:32)
    at org.commonreality.mina.service.ClientService$5.handleMessage(ClientService.java:164)
    at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:232)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
    at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
    at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:780)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:772)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:714)
    at org.commonreality.executor.GeneralThreadFactory$1.run(GeneralThreadFactory.java:85)
    at java.lang.Thread.run(Thread.java:745)

Jan 08, 2016 9:32:14 PM org.commonreality.reality.impl.DefaultReality$1 lambda$opened$24
SEVERE: Exception caught from org.commonreality.mina.MINASessionInfo@77a87016, closing 
java.lang.NullPointerException
    at org.commonreality.reality.impl.StateAndConnectionManager.participantState(StateAndConnectionManager.java:1416)
    at org.commonreality.reality.impl.handler.ConnectionAckHandler.accept(ConnectionAckHandler.java:44)
    at org.commonreality.reality.impl.handler.ConnectionAckHandler.accept(ConnectionAckHandler.java:24)
    at org.commonreality.mina.service.ServerService$5.handleMessage(ServerService.java:162)
    at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:232)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
    at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
    at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:780)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:772)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:714)
    at org.commonreality.executor.GeneralThreadFactory$1.run(GeneralThreadFactory.java:85)
    at java.lang.Thread.run(Thread.java:745)

Jan 08, 2016 9:32:14 PM org.commonreality.reality.impl.StateAndConnectionManager setState
SEVERE: Could not set [AGENT:5:agent:1052020421] to RESET. Flagging as unresponsive. 
java.lang.NullPointerException
    at org.commonreality.net.message.command.control.IControlCommand$State.equivalentTo(IControlCommand.java:51)
    at org.commonreality.reality.impl.StateAndConnectionManager.setState(StateAndConnectionManager.java:756)
    at org.commonreality.reality.impl.DefaultReality.setParticipantStates(DefaultReality.java:278)
    at org.commonreality.reality.impl.DefaultReality.reset(DefaultReality.java:344)
    at org.commonreality.reality.RealityTest.testMockSensor(RealityTest.java:208)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:255)
    at junit.framework.TestSuite.run(TestSuite.java:250)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Jan 08, 2016 9:32:14 PM org.commonreality.reality.impl.StateAndConnectionManager setState
SEVERE: Could not set [SENSOR:3:mock:-773770318] to RESET. Flagging as unresponsive. 
java.lang.NullPointerException
    at org.commonreality.net.message.command.control.IControlCommand$State.equivalentTo(IControlCommand.java:51)
    at org.commonreality.reality.impl.StateAndConnectionManager.setState(StateAndConnectionManager.java:756)
    at org.commonreality.reality.impl.DefaultReality.setParticipantStates(DefaultReality.java:278)
    at org.commonreality.reality.impl.DefaultReality.reset(DefaultReality.java:344)
    at org.commonreality.reality.RealityTest.testMockSensor(RealityTest.java:208)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at junit.framework.TestSuite.runTest(TestSuite.java:255)
    at junit.framework.TestSuite.run(TestSuite.java:250)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Jan 08, 2016 9:32:14 PM org.commonreality.reality.impl.DefaultReality$1 lambda$opened$24
SEVERE: Exception caught from org.commonreality.mina.MINASessionInfo@5aa9ccaf, closing 
java.lang.NullPointerException
    at org.commonreality.reality.impl.StateAndConnectionManager.participantState(StateAndConnectionManager.java:1416)
    at org.commonreality.reality.impl.handler.ConnectionAckHandler.accept(ConnectionAckHandler.java:44)
    at org.commonreality.reality.impl.handler.ConnectionAckHandler.accept(ConnectionAckHandler.java:24)
    at org.commonreality.mina.service.ServerService$5.handleMessage(ServerService.java:162)
    at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:232)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
    at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
    at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:780)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:772)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:714)
    at org.commonreality.executor.GeneralThreadFactory$1.run(GeneralThreadFactory.java:85)
    at java.lang.Thread.run(Thread.java:745)

Jan 08, 2016 9:32:14 PM org.commonreality.participant.impl.AbstractParticipant$2 lambda$opened$20
SEVERE: Exception caught from org.commonreality.mina.MINASessionInfo@519ab1ca, closing 
java.lang.RuntimeException: java.lang.NullPointerException
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:216)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:32)
    at org.commonreality.mina.service.ClientService$5.handleMessage(ClientService.java:164)
    at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:232)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
    at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
    at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:780)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:772)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:714)
    at org.commonreality.executor.GeneralThreadFactory$1.run(GeneralThreadFactory.java:85)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.commonreality.participant.impl.handlers.ControlHandler.setState(ControlHandler.java:117)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:186)
    ... 14 more

Jan 08, 2016 9:32:14 PM org.commonreality.participant.impl.AbstractParticipant$2 lambda$opened$20
SEVERE: Exception caught from org.commonreality.mina.MINASessionInfo@1469913b, closing 
java.lang.RuntimeException: java.lang.NullPointerException
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:216)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:32)
    at org.commonreality.mina.service.ClientService$5.handleMessage(ClientService.java:164)
    at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:232)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
    at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
    at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
    at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:780)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:772)
    at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:714)
    at org.commonreality.executor.GeneralThreadFactory$1.run(GeneralThreadFactory.java:85)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.commonreality.participant.impl.handlers.ControlHandler.setState(ControlHandler.java:117)
    at org.commonreality.participant.impl.handlers.ControlHandler.accept(ControlHandler.java:186)
    ... 14 more

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.077 sec
Running org.commonreality.net.SimpleNetProviderTest
Jan 08, 2016 9:32:14 PM org.commonreality.net.SimpleNetProviderTest testNIOSerializer
WARNING: Not strictly a proper test. This will not fail short of an exception

Jan 08, 2016 9:32:15 PM org.commonreality.net.SimpleNetProviderTest testNIOSerializer
WARNING: Not strictly a proper test. This will not fail short of an exception

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.078 sec

Results :

Tests run: 17, Failures: 0, Errors: 0, Skipped: 0

**Comment by amharrison** [comment]
Ack. This is embarrassing. This is actually residual cruft from me not updating the io tests to use the netty provider. Hoping to have some time in the next few weeks to work on some of the technical debt.

**Comment by monochromata** [comment]
Cool :-) maybe it's better if I finish the migration to Maven first before we do a lot of other stuff, because I move around a lot of files to make them fit to standard Maven conventions. It might become a bit messy / merge conflicts may arise if we both modify files.
